# Site settings
title: Mixtape Haven
description: Your private, ad-free music sanctuary. Rediscover the art of the mixtape.
url: "https://jaxkodex.github.io" # the base hostname & protocol for your site
baseurl: "/mixtapehaven-docs" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
